version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins/jenkins:lts
    container_name: supplychainx-jenkins
    privileged: true
    user: root
    restart: unless-stopped
    ports:
      - "8090:8080"
      - "50000:50000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    dns_search:
      - maven.apache.org
    environment:
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.mvn/settings.xml:/var/jenkins_home/.m2/settings.xml:ro
    networks:
      - scx-network
    extra_hosts:
      - "repo.maven.apache.org:151.101.1.209"
      - "repo.maven.apache.org:151.101.65.209"

volumes:
  jenkins_home:
    driver: local

networks:
  scx-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: scx-bridge
      com.docker.network.driver.mtu: 1500

